In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
import joblib
import os
os.chdir('Resources/')

from custom_tuple_scaler import CustomTupleScaler  

In [2]:
df = pd.read_csv('21_(SYS)_CR_Encrypted_User_Data.csv')
df.head()

Age  \
0  (116117118567918454538443635441930044584366525...   

                                                 Sex  \
0  (115216133156897905997902213226564416198983593...   

                                       ChestPainType  \
0  (534062771043874878230123617229893967373724032...   

                                RestingBloodPressure  \
0  (295979949112269684481418694088532144415321623...   

                                         Cholesterol  \
0  (257274593255949905354701935391895385009626884...   

                                   FastingBloodSugar  \
0  (899127013110631706582825959635648121268124629...   

                                          RestingECG  \
0  (373404129004605616061391413657108570512290097...   

                                    MaximumHeartRate  \
0  (116079673230625493169642312195399383672533140...   

                                      ExerciseAngina  \
0  (136471690382529317079093051788397747452273532...   

                                             Oldpeak  \
0  (212717196627388261638670485566983487486220007...   

                                            ST_Slope  
0  (953373854764096036137291734717058396988185634...

In [3]:
custom_scaler = joblib.load('13_CC_Scaler.joblib')

df_scaled = custom_scaler.transform(df)

df_scaled = pd.DataFrame(df_scaled, columns=df.columns)

print(df_scaled)

        Age       Sex  ChestPainType  RestingBloodPressure  Cholesterol  \
0  0.411571 -0.574685       -0.22904              0.883218    -0.586446   

   FastingBloodSugar  RestingECG  MaximumHeartRate  ExerciseAngina   Oldpeak  \
0            1.95009    1.065109         -0.147421       -0.825528  0.011132   

   ST_Slope  
0  1.024518  


g:\Thesis - Copy\Resources\custom_tuple_scaler.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  c2_values = X.applymap(self._extract_c2)


In [4]:
model = joblib.load('12_SP_Model_RF_IF_3.joblib')

In [5]:
prediction = model.predict(df_scaled)
prediction

array([1], dtype=int64)

In [6]:
prediction_prob = np.round(model.predict_proba(df_scaled) * 100, 2)
prediction_prob

array([[36.28, 63.72]])

In [7]:
prediction_prob_class_1 = model.predict_proba(df_scaled)[:, 1][0]
feature_importance = model.feature_importances_
feature_contributions = np.round(feature_importance * prediction_prob_class_1 * 100, 2)
feature_contributions

array([ 6.52,  1.55, 10.21,  7.09,  8.11,  1.68,  4.62,  7.59,  2.07,
        6.15,  8.12])

In [8]:
prediction_value = int(prediction[0])

output_data = [prediction_value] + [prediction_prob[0][0]] + [prediction_prob[0][1]] + feature_contributions.tolist()
output_data


[1,
 36.28,
 63.72,
 6.52,
 1.55,
 10.21,
 7.09,
 8.11,
 1.68,
 4.62,
 7.59,
 2.07,
 6.15,
 8.12]

In [9]:
pd.DataFrame([output_data]).to_csv("22_(SYS)_CC_Predicted_User_Output_Data.csv", index=False, header=False)